# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4e2e6824412eb95824c07f86c450a5af365fcea9beb4daad50d9c94483c88df4db0c981ff6fc1611054b9073f5fc85f561324c432b666c35107f02c58fb6c00

test:
  secret_key_base: f86db7587493cd6f92fb0327f37f8ae0d544e81d035946a86dc533e583c3158d5ef82a4f533d20ec4dfcb1ede11c1d24d303e0c879612b877dec682745eb7ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
